### ISSUE TITLE
Axes x and y coordinates cannot be integers, but standard doesn't prohibit this

### ISSUE THREAD

**Issue by petergarnaes** [KNMI/covjson-pydantic#14]
I'm creating CoverageJSON objects with coordinates from a UTM coordinate system, where the coordinates are whole numbers. As far as I can tell from the standard section 9.6.1.1 it is not a requirement for these coordinates to be float, in fact the word `int` or `float` is never mentioned.

However the code for the Axes class states:
```python
class Axes(CovJsonBaseModel):
    x: Optional[Union[ValuesAxis[float], CompactAxis]] = None
    y: Optional[Union[ValuesAxis[float], CompactAxis]] = None
    ...
```

Shouldn't it be:
```python
class Axes(CovJsonBaseModel):
    x: Optional[Union[ValuesAxis[Union[float, int]], CompactAxis]] = None
    y: Optional[Union[ValuesAxis[Union[float, int]], CompactAxis]] = None
    ...
```
The same goes for CompactAxis:
```python
class CompactAxis(CovJsonBaseModel):
    start: float
    stop: float
    ...
```

**Comment by PaulVanSchayck** [comment]
Thank you for reporting. I think you may be right. They specify "number", which I think should be interpreted as float or int. JSON itself doesn't make a clear distinction between the two. 

I think the specs are even saying the Axis object values may be strings. However CompactAxis start and stop can be numbers, num should be an integer. 

I've opened a PR: https://github.com/KNMI/covjson-pydantic/pull/15

**Comment by PaulVanSchayck** [comment]
After some more careful consideration, we believe that `ValuesAxis[int]` is not a correct type to have.

CoverageJSON is in the first place a specification on top of the [JSON specification](https://datatracker.ietf.org/doc/html/rfc8259#section-6). JSON specifies numbers to contain an integer component that may be  prefixed with an optional minus sign, which may be followed by a fraction part and/or an exponent part. The most correct representation of this type in Python would be `float`.

Could you explain why there would be an issue with representing your coordinates as `float` type? If you're worried about precision, this should not be an issue. All integers in the range [`-(2**53)+1`, `(2**53)-1`] can be represented exactly in the `float` type (i.e `1.0 == 1`). 

We have added `ValuesAxis[str]` in PR #15.

**Comment by petergarnaes** [comment]
> Could you explain why there would be an issue with representing your coordinates as float type?

There is not a problem in doing so, my coordinates are integers within the range you provide. But since my coordinates actually are integers, and both JSON and CoverageJSON allows for using integers, I would expect that I would be able to return CoverageJSON with integers in coordinates.

The coordinates in question is the Danish National Grid, which is based on EPSG:32632 / UTM zone 32N and only uses coordinates that are integers / no decimals.

If including `int` is deemed out of scope, feel free to close the issue.
