### ISSUE TITLE
Missing cs in referencing -> coordinates -> system

### ISSUE THREAD

**Issue by ways** [KNMI/covjson-pydantic#7]
Please look at https://docs.ogc.org/cs/21-069r2/21-069r2.html -> Annex A -> Coverage Examples -> A.1.  Vertical Profile Coverage which looks like this:

```
    "referencing": [{
      "coordinates": ["z"],
      "system": {
        "type": "VerticalCRS",
        "cs": {
          "csAxes": [{
            "name": {
              "en": "Pressure"
            },
            "direction": "down",
            "unit": {
              "symbol": "Pa"
            }
          }]
        }
      }
    }
```

I can't find any field "cs" in class ReferenceSystem at https://github.com/KNMI/covjson-pydantic/blob/e74abaadfecd605ce1dea05643dfa3434620e211/src/covjson_pydantic/reference_system.py#L20C1-L20C1

The class allows for "extra", so one can add non-defined fields. How to do that in a correct manner?

**Comment by PaulVanSchayck** [comment]
Yes, that's possible. This particular example you link from the docs was already included in our automatic tests. But see this code for an standalone example:
```
from datetime import datetime
from datetime import timezone

from covjson_pydantic.coverage import Coverage
from covjson_pydantic.domain import Axes
from covjson_pydantic.domain import Domain
from covjson_pydantic.domain import DomainType
from covjson_pydantic.domain import ValuesAxis
from covjson_pydantic.ndarray import NdArray
from pydantic import AwareDatetime
from covjson_pydantic.reference_system import ReferenceSystem, ReferenceSystemConnectionObject

c = Coverage(
    domain=Domain(
        domainType=DomainType.point_series,
        axes=Axes(
            x=ValuesAxis[float](values=[1.23]),
            y=ValuesAxis[float](values=[4.56]),
            t=ValuesAxis[AwareDatetime](values=[datetime.now(tz=timezone.utc)]),
        ),
        referencing=[ReferenceSystemConnectionObject(
            coordinates=["z"],
            system=ReferenceSystem(
                type="VerticalCRS",
                cs={'csAxes': [{'name': {'en': 'Pressure'}, 'direction': 'down', 'unit': {'symbol': 'Pa'}}]}
            )
        )]
    ),
    ranges={"temperature": NdArray(axisNames=["x", "y", "t"], shape=[1, 1, 1], values=[42.0])},
)

print(c.model_dump_json(exclude_none=True, indent=4))
```

However, note that there is a bit of discrepancy in the spec. The spec notes in [section 9.5](https://docs.ogc.org/cs/21-069r2/21-069r2.html#_03c5e6a3-4543-404e-b170-2ba4e495cf26): "Custom values MAY be used as detailed in the [Extensions](https://docs.ogc.org/cs/21-069r2/21-069r2.html#extensions) section."

In this Extensions section it notes "If a custom member is added to a CoverageJSON document, its name SHOULD be a compact URIs of the form "prefix:suffix".". 

So this example the `cs` part of `ReferenceSystem()` should be something like `prefix:cs`. Where prefix is registered prefix.

**Comment by ways** [comment]
Thank you for the clarification and example :+1:
